import pytest
import numpy as np
from symbolic_alpha.ast_generator import (
    ASTGenerator
)
from symbolic_alpha.evaluator import ChimeraEngine

@pytest.fixture(scope="module")
def engine():
    eng = ChimeraEngine(capacity_rows=1000)
    yield eng
    eng.close()

def test_ast_depth_constraint():
    gen = ASTGenerator(num_features=10, max_depth=4)
    for _ in range(100):
        tree = gen.random_tree(max_depth=4)
        assert tree.depth() <= 4, f"Tree exceeded max depth 4: {tree.depth()}"

def test_ast_bytecode_compilation_and_execution(engine):
    gen = ASTGenerator(num_features=5, max_depth=3)
    features = np.random.randn(100, 5).astype(np.float32)

    for _ in range(50):
        tree = gen.random_tree(max_depth=3)
        instructions = tree.compile_to_bytecode()
        assert len(instructions) > 0
        output = engine.execute(instructions, features)
        assert output.shape == (100,)
        assert not np.isnan(output).any(), f"NaN generated by tree: {tree.to_formula()}"

def test_point_mutation():
    gen = ASTGenerator(num_features=10, max_depth=4)
    tree = gen.random_tree(max_depth=3)
    mutated = gen.mutate(tree)
    assert mutated is not None
    assert mutated.depth() <= 4

def test_subtree_crossover():
    gen = ASTGenerator(num_features=10, max_depth=4)
    parent1 = gen.random_tree(max_depth=3)
    parent2 = gen.random_tree(max_depth=3)
    child1, child2 = gen.crossover(parent1, parent2)
    assert child1.depth() <= 4
    assert child2.depth() <= 4

def test_stochastic_robustness(engine):
    gen = ASTGenerator(num_features=8, max_depth=4)
    features = np.random.randn(50, 8).astype(np.float32)
    
    # Generate 200 random trees, perform mutations and crossovers, then execute
    pop = [gen.random_tree(max_depth=3) for _ in range(50)]
    for i in range(len(pop) - 1):
        c1, c2 = gen.crossover(pop[i], pop[i+1])
        c1 = gen.mutate(c1)
        instructions = c1.compile_to_bytecode()
        out = engine.execute(instructions, features)
        assert out.shape == (50,)
